### ISSUE TITLE
Provide instructions for the .env file in the readme

### ISSUE THREAD

**Issue by leovdd** [nerdland-unofficial-fans/nerdlandbot#118]
** I struggled a bit to get my bot working because of the .env file requirements, so I'd like to help noobs like me**

- Instruction on where to create the .env file
- Example of what should be in the .env file (faking the token obv.)

**Comment by leovdd** [comment]
Waarom heb ik dit in het Engels geschreven ? Nobody knows...
Anyway, ik zou het ook graag zelf doen om de cyclus van branching, pull request, enz.. es door te lopen.

**Comment by woutermeuwis** [comment]
We prefer english while developing, we agree with your original language choice :D

**Comment by DrSkunk** [comment]
It seems that you fixed this, so I think it's safe to say to close this? If not, you can re-open.
