### ISSUE TITLE
Make bot be friendly on the weekends

### ISSUE THREAD

**Issue by bobvdvleuten** [nerdland-unofficial-fans/nerdlandbot#119]
**Is your feature request related to a problem? Please describe.**
Nope, just would be nice if he says "schat" instead of "foemp" in the weekend 

**Describe the solution you'd like**
On Saturdays and Sundays, any message texts sent by the bot have `Foemp` replaced by `Schat`

**Describe alternatives you've considered**
Letting the bot be a potty mouth for the rest of its days

**Additional context**
`Schat` is a reference to the legendary Robbe De Hert.

**Comment by woutermeuwis** [comment]
This would require a refactor though, as the foemp is currently hardcoded in the translations and should as such be abstracted.

**Comment by bobvdvleuten** [comment]
It would indeed not be an easy one to implement, but here's to the brave soul who'll try.

**Comment by VandeVelGianni** [comment]
Wouldn't it be as easy as extracting the "foemp" out of the CSV, replacing it with a {0} or whatever they call that and then using some logic to determine if it should be "foemp" or "schat"?
