### ISSUE TITLE
Update the "!help notify" command.

### ISSUE THREAD

**Issue by VandeVelGianni** [nerdland-unofficial-fans/nerdlandbot#126]
**Describe the bug**
The "!help notify"-command doesn't mention anything about the [message]-aspect of the "!notify"-command.

**To Reproduce**
1. Use "!help notify"
2. Be confused

**Expected behavior**
A clear and concise description of what you expect to happen when using the "!help notify"-command

**Screenshots**

**Additional context**

**Comment by VandeVelGianni** [comment]
The solution has been approved, waiting for the merge. This can be closed, I assume.

**Comment by woutermeuwis** [comment]
Merged it, although usually an issue is closed after the merge ;)

**Comment by VandeVelGianni** [comment]
Oh, oops. I'll keep that in mind for the future.
