### ISSUE TITLE
!open_source command

### ISSUE THREAD

**Issue by VandeVelGianni** [nerdland-unofficial-fans/nerdlandbot#128]
**Is your feature request related to a problem? Please describe.**
Sometimes people want to suggest features and they do so in the chat, while they can just make a GitHub account and help developing the bot.

**Describe the solution you'd like**
A simple command that explains that the bot is open source, that they can work on it themselves and that their work might show up in a deployed build.

**Describe alternatives you've considered**
/

**Additional context**
This was talked about in the #steljevoor channel.

**Comment by VandeVelGianni** [comment]
I'd love to take a swing at this one, if that's ok.

**Comment by leovdd** [comment]
I guess that's ok ? 
Make sure to assign yourself to it and create a branch referring to the ticket so we don't do double work.

**Comment by woutermeuwis** [comment]
permission issue, on it :)
