### ISSUE TITLE
Periodically post a message

### ISSUE THREAD

**Issue by woutermeuwis** [nerdland-unofficial-fans/nerdlandbot#13]
TBD

**Comment by bobvdvleuten** [comment]
What's the idea here @woutermeuwis ?

**Comment by woutermeuwis** [comment]
Well, to periodically post a message 😅 
I don't remember why, but at some point someone requested this 😂

**Comment by bobvdvleuten** [comment]
a random message? that could be fun.

how about we make it random quotes instead and they come from a quote repository based on nerland discord users' notable quotes.

**Comment by woutermeuwis** [comment]
If i remember correctly the intention was for this to be configurable.

For example asking the bot to post something every hour.
This could either be a simple message, or actually be a command.

I could for example ask the bot to say ?membercount each hour, triggering it to actually log the membercount.

But once again, it's just vaguely in my memory :p

**Comment by DrSkunk** [comment]
Is this issue still relevant? If yes, you can re-open.
