### ISSUE TITLE
Keep track of notify list creation, last use and usage count

### ISSUE THREAD

**Issue by ThunderbirdOne** [nerdland-unofficial-fans/nerdlandbot#141]
We've noticed that the sub list is getting rather long and that some of the lists don't seem to get used a lot.

To make it easier for the mods we could add "audit" fields in the config.
I suggest the following fields:
- date_created
- last_notified
- notify_count (as a bonus, keep notification dates in an array for more statistics)

As an extra it might be nice to have a command (admin only) that sends stats for a specific list in a DM?

**Comment by ThunderbirdOne** [comment]
While fixing this issue I decided it might be easier to just track the datetimes of when notifications happen. This allows us to both get the last_notified time and also the notify_count.

The only thing that might be an issue is the notified_on list getting very long in the guild_config. 

The DM stat thing should probably be split off into its own issue.

**Comment by evasmeets** [comment]
You could send the stats in the #logs channel instead of in a DM
