### ISSUE TITLE
Nerdtalks ical

### ISSUE THREAD

**Issue by thomashertog** [nerdland-unofficial-fans/nerdlandbot#150]
As a bot admin/nerdland moderator/...
I would like to have calendar functionality 
In order to manage nerdtalks more efficiently

Scenario: add nerdtalks
Given a public nerdland calendar (Google, Outlook, ...) in .ics/.ical format
When someone announces they want to do a nerdtalk
And I add them to the calendar through the bot
Then I can see them appearing in the public nerdland calendar

Scenario: overview nerdtalks
Given some announced nerdtalks
And a public nerdland calendar in .ics/.ical format
When I want to know when nerdtalks are happening
Then I can import the .ics/.ical calendar into my favourite calendar app
And nerdlandbot can once in a while keep everyone posted with generated notifications in Discord

**Comment by bobvdvleuten** [comment]
seems a duplicate of #116 ,no?

**Comment by thomashertog** [comment]
duplicate issue indeed, hadn't checked the open issues
