### ISSUE TITLE
Invisible moderator tagging/DM

### ISSUE THREAD

**Issue by Vobtex** [nerdland-unofficial-fans/nerdlandbot#164]
As a Discord community grows, it tends to attract trolls. Some of these trolls are just in it for the gratification of having a moderator called in, as a weird form of attention-seeking behaviour. We've seen this occur a few times now in the Nerdland server.
To circumvent this problem, I would suggest a function where a Direct Message (DM) can be sent to the bot, which will then be forwarded to either a DM for all of the moderators (individually or some sort of group-DM) or to a moderator-only channel within the server where they are tagged.

It seems like a somewhat overengineered solution, but I think it will take away a part of the motivation behind trolling behaviour, namely the feeling of gratification whenever they are given attention from 'high ranked' individuals.

As always : this is just a suggestion, if you feel it is not worth the effort or have other comments: let me know :)

**Comment by VandeVelGianni** [comment]
Great idea! 👍

**Comment by Eva774** [comment]
I'd like to look into the implementation of this feature :)
