### ISSUE TITLE
Feature for pictures of pets

### ISSUE THREAD

**Issue by Eva774** [nerdland-unofficial-fans/nerdlandbot#170]
**This issue is more a start of an idea rather than a fully formed idea for a feature, so please comment with any further ideas or remarks. If we decide to implement this, I'd like to give this a go, it seems like a fun feature to work on**

We could make a feature with a `!pet` command.
- Pictures can be added with `!add_pet` and the bot would download them and put them in a folder.
- With `!pet` the bot would then post a random picture from that folder.

**Pitfalls and open questions**
1. You would need a way to delete pictures through the bot. I think if we give every picture a number and save it with that number as well (so just 7.jpg for example) and when the bot posts the picture, he also says "this is picture 7", the picture could be easily deleted with `!del_pet 7`. I think it would look a bit weird if the bot says the picture number every time, but I can't really think of another easy way to identify the pictures. 

2. If we allow all users to add pictures, I think it is a matter of time before someone adds a NSFW type picture or people start 'abusing' the feature to add random pictures instead of pets. I see three options here:
-  Accept that this will happen and delete those unwanted pictures
- Only allow bot_admins to add pictures.
- Keep a list of verified pet owners (such as Thibaut, Karen, Andreas, ...) where the bot admins can add or remove people and only allow those people to add pictures.

3. For deleting pictures I think there could be a similar issue: people could start trolling and delete pictures that are not unwanted. For this issue I think there are the same three options as with the issue about adding pictures.

4. Do we categorize the pictures or not? We could let the pictures be added by pet name for example and then people could use `!pet <name>` to only get pictures of that pet. To make this distinction I think the name would have to be in the filename, or we could have keep a separate json file with all the 'metadata'. If we keep this json we could also start making the distinction between for example cats and dogs as well.

5. Privacy wise I think we should only allow people to add pictures of their own pet, but I don't really know how to enforce this.

**Comment by bobvdvleuten** [comment]
on point 2 i would opt for option 1. 
It's no different from people posting unwanted stuff now. 
Potentially should just have a feature for admins to easily remove photos (EDIT: just saw point 1 and agree with that) and limit the number of times a user can call the command within 24hrs to avoid spam?


point 3: For Deleting pictures: would only allow admins and users who added them to delete them.

point 4: big fan of that idea, can also resolve point 3 by keeping the user id in the json for the deletion rights (not for telling people who's pet it is)

point 5: not a tooling issue but a use issue. So don't see a technical way to resolve but also don't see a high risk on this. If admins can delete then we're good.

**Comment by bobvdvleuten** [comment]
For Deleting pictures: would only allow admins and users who added them to delete them.

**Comment by Eva774** [comment]
> It's no different from people posting unwanted stuff now.

The difference I see is that the unwanted stuff people post now usually doesn't get reposted later. If an unwanted image gets added and for some reason no admins see it, it won't get deleted which means it could be reposted later on. But I am not sure whether this is a problem I created in my head or whether it is an actual problem.

We can always start with option 1 (let everyone add pictures) since it is takes no extra implementation anyway and if we see that it goes wrong, we can always change it later.

**Comment by bobvdvleuten** [comment]
> But I am not sure whether this is a problem I created in my head or whether it is an actual problem.

It's a genuine risk, but the risk is very small so I would not try to mitigate it upfront and thereby limiting the FUNctionality :)

**Comment by VandeVelGianni** [comment]
I like it. Agree with Bob on most points. 

The only thing I wouldn't do is the 24hr limit. It seems arbitrary to me and would limit the functionality in the beginning when not a lot of pictures have been added, unless you set it at a reasonably high threshold.

**Comment by Eva774** [comment]
Regarding the limit, we can use the same strategy: don't implement it at the start and if it appears to be necessary we can always implement it later.
