### ISSUE TITLE
Subscribe to lists with reactions

### ISSUE THREAD

**Issue by Eva774** [nerdland-unofficial-fans/nerdlandbot#20]
To make the bot add a reaction to a message: https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.add_reaction
For reacting with standard discord emojis you need a unicode string for the emoji.

To make the bot listen to reactions on a message it has just sent: https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=wait_for#discord.ext.commands.Bot.wait_for 
wait_for only waits for reactions to a message it has just sent, you can make it listen to all reactions before a certain time has passed, so other users than the ctx.author could also react to that message to add themselves to a list. You could technically keep waiting indefinitely for reactions, but this is desired, an on_reaction_add event is probably better.

To make the bot listen to all reactions added to all messages (not just his own): https://discordpy.readthedocs.io/en/latest/api.html#discord.on_reaction_add 
this processes all reactions, but you can check if it is a reaction to a message to sub to a list with the message ID. With this, there are 2 options that I see: 
- The bot mirrors the original post with its reactions everytime a user wants to sub, this way it only needs to listen to that specific message.
- The bot posts a new message when a user wants to sub and adds the ID of that message to a list of messages to listen to.

**Comment by woutermeuwis** [comment]
I think this is fully implemented now?

**Comment by Eva774** [comment]
Jup I think so too
