### ISSUE TITLE
Bot Admin access

### ISSUE THREAD

**Issue by woutermeuwis** [nerdland-unofficial-fans/nerdlandbot#22]
Currently the bot restricts certain commands to discord admins.
It should be possible to give discord users admin rights for the bot, without handing out actual discord admin rights.

**Comment by Eva774** [comment]
https://github.com/nerdland-unofficial-fans/nerdlandbot/pull/39[](url)

**Comment by Eva774** [comment]
#39

**Comment by bobvdvleuten** [comment]
should be closed once #39 has been merged
