### ISSUE TITLE
Subsribe lists

### ISSUE THREAD

**Issue by Eva774** [nerdland-unofficial-fans/nerdlandbot#4]
Lijsten met mensen die bijvoorbeeld allemaal hetzelfde spel spelen, zodat je ze als groep kan taggen als je iemand zoekt om mee te spelen. Of bijvoorbeeld alle mensen die een bepaalde programmeertaal goed kennen zodat je ze kan taggen als je hulp zoekt. In de lijsten zouden dan allemaal strings staan van de mensen die toegevoegd zijn.

Mogelijke commands:
? subscribe [listname] -> zodat mensen zichzelf kunnen toevoegen aan een bepaalde lijst. Als de lijst nog niet bestaat kan er mogelijk een nieuwe lijst gemaakt worden, eventueel met een check of de naam veel lijkt op de naam van een bestaande lijst.  (bv dat de bot stuurt: "bedoel je csgo?" als je csho typt)

?unsubscribe [listname/all] -> om jezelf uit een lijst te kunnen halen

?subscriptions -> om te kijken bij welke lijsten je allemaal zit

?showlists -> om te kijken welke lijsten er allemaal bestaan

?notify [listname] of ?notify [listname] [message] -> om alle gebruikers in een lijst te taggen in discord, eventueel met bericht

**Comment by flor01** [comment]
Is het goed dat ik dit maak?

**Comment by woutermeuwis** [comment]
Dit zou nog verder uitgebreid moeten worden met wat extra info in het help commando.
Elk command zou op zijn minst een korte description moeten hebben :)
