### ISSUE TITLE
Purge channel

### ISSUE THREAD

**Issue by woutermeuwis** [nerdland-unofficial-fans/nerdlandbot#80]
**Is your feature request related to a problem? Please describe.**
Some channels contain sensitive data, and should be purged every now and then.

**Describe the solution you'd like**
A command to schedule a daily purge on a channel for messages that exceed a given age.
Important note: Pinned message should not be purged!

**Additional context**
![image](https://user-images.githubusercontent.com/15607234/99371411-289a5680-28bf-11eb-805c-50b1cc6b7068.png)

**Comment by DrSkunk** [comment]
In the [YouTube notification feature](https://github.com/nerdland-unofficial-fans/nerdlandbot/issues/76) a method was added to do scheduled tasks. The first steps for a scheduler were started [here](https://github.com/nerdland-unofficial-fans/nerdlandbot/blob/440290dc54e6da49197e09d532eda52eee761502/Scheduler/Scheduler.py).

This method can be extended in the same way.

**Comment by bobvdvleuten** [comment]
happy to try and implement this but we'll need a specific test channel for this on the bot Discord for testing.
What timeline would we be looking at? 30 days?

**Comment by bobvdvleuten** [comment]
For pinned messages there could be a workaround in having the bot repost them and pin them using msg.pin()

**Comment by woutermeuwis** [comment]
Tim was planning to do this, still have to add him to the github.
Also, no need to repost the pinned message, have a look at the check param in the docs above ;)

**Comment by bobvdvleuten** [comment]
Yeah, missed that. In that case will not work on this one or check with Tim to collaborate if he wants.
