### ISSUE TITLE
stats van reactions

### ISSUE THREAD

**Issue by thomashertog** [nerdland-unofficial-fans/nerdlandbot#89]
als we statistieken bijhouden van reacties op messages kunnen we een Gouden Jas uitreiken op de Discord!
degene die de meeste verzamelt, krijgt een gratis curryworst/frikandel/lange hamburger bij de meetup

**Comment by Brammm** [comment]
Holy fuck da's echt een legit idee. Kunnen we zo wa algemene dingen bijhouden? Wie maakt het meest dt fouten, wie is dubbelzinnigst (📼 ) etc

**Comment by thomashertog** [comment]
ik heb zo mijn ideeën 😂 tegelijkertijd, het moet vooral niet competitief worden ofzo, dat zou alleen maar jammer zijn

**Comment by bobvdvleuten** [comment]
This one clashes with the privacy policy of the bot, I fear.
