### ISSUE TITLE
Automatisch verwijderen dt emoji na edit

### ISSUE THREAD

**Issue by Brammm** [nerdland-unofficial-fans/nerdlandbot#90]
Wanneer je een edit doet (eventueel zelfs met detectie op d/t letters) zou het tof zijn als de dt emoji automatisch verwijdert word.

**Comment by thomashertog** [comment]
*verwijderd 😂

**Comment by bobvdvleuten** [comment]
Might not be possible since the bot does not have any privileges over the messages and reactions of other users.

**Comment by thomashertog** [comment]
What might be an alternative is that you sent a notification to the dt-givers to remove their reaction?
that requires them to review whether the mistake has been fixed (instead of editing the message and still have an error in there)

**Comment by DrSkunk** [comment]
Since the bot doesn't have privileges to edit messages of other people, I think it's best to close this one.
